version: '3.7'

services:
  solr:
    # image: solr:8.4.1
    ports:
      - "8983:8983"
    build: .
    container_name: solr-server
    volumes:
      - ./searchpages-solr:/var/solr/data/searchpages
      # - ./custom.sh:/docker-entrypoint-initdb.d/custom.sh

