version: '3.7'

services:
  solr:
    # image: solr:8.4.1
    ports:
      - "8983:8983"
    build: ./solr
    container_name: solr-server
    volumes:
      - ./solr/searchpages-solr:/var/solr/data/searchpages
      # - ./custom.sh:/docker-entrypoint-initdb.d/custom.sh

  api:
    build: ./page-search-api
    container_name: pagesearch
    ports:
      - "8081:8081"


