version: '3.7'

services:
  solr:
    # image: solr:8.4.1
    ports:
      - "8983:8983"
    build: ./solr
    container_name: pagesearch-solr-test
    volumes:
      - ./solr/pagesearch-solr:/var/solr/data/pagesearch

  api:
    build: ./page-search-api
    container_name: pagesearch
    ports:
      - "8081:8081"


